import type { FairnessMetadata, EngineInput, GeneratedMatch, GeneratedSitOut } from "./types.js";
import { ALGORITHM_VERSION } from "./types.js";
import type { EngineState } from "./state.js";

export function computeFairness(
  state: EngineState,
  output: { matches: GeneratedMatch[]; sitOuts: GeneratedSitOut[] },
  input: EngineInput
): FairnessMetadata {
  const games = Array.from(state.gamesPlayed.values());
  const sitOuts = Array.from(state.sitOuts.values());

  // No players / no rounds generated: return neutral metadata (avoid Math.max(...[]) → -Infinity/NaN).
  if (games.length === 0) {
    return {
      algorithmVersion: ALGORITHM_VERSION,
      playersCount: input.players.length,
      courtsCount: input.courts.length,
      roundsGenerated: new Set(output.matches.map((m) => m.roundNumber)).size,
      fairnessScore: 1,
      minGamesPerPlayer: 0,
      maxGamesPerPlayer: 0,
      notes: [],
    };
  }

  const minGames = Math.min(...games);
  const maxGames = Math.max(...games);

  let penalty = 0;
  const notes: string[] = [];

  // 1. Games played spread
  const maxSpread = maxGames - minGames;
  if (maxSpread > 1) {
    penalty += 0.2 * (maxSpread - 1);
    notes.push(`Games played spread is ${maxSpread} (ideal is ≤ 1)`);
  }

  // 2. Sit-outs spread (sitOuts is non-empty whenever games is)
  const sitOutSpread = Math.max(...sitOuts) - Math.min(...sitOuts);
  if (sitOutSpread > 1) {
    penalty += 0.3 * (sitOutSpread - 1);
    notes.push(`Sit-out spread is ${sitOutSpread} (ideal is ≤ 1)`);
  }

  // 3. Repeat partners/opponents (check highest values)
  const maxPartners = Math.max(...Array.from(state.partnerCount.values()), 0);
  if (maxPartners > 1) {
    penalty += 0.1 * (maxPartners - 1);
    notes.push(`Repeated partners detected (max times: ${maxPartners})`);
  }

  const fairnessScore = Math.max(0, Math.min(1, 1 - penalty));

  // Count rounds generated by looking at output matches
  const roundsSet = new Set(output.matches.map(m => m.roundNumber));
  const roundsGenerated = roundsSet.size;

  return {
    algorithmVersion: ALGORITHM_VERSION,
    playersCount: input.players.length,
    courtsCount: input.courts.length,
    roundsGenerated,
    fairnessScore,
    minGamesPerPlayer: minGames,
    maxGamesPerPlayer: maxGames,
    notes,
  };
}