import type { FairnessMetadata, EngineInput, GeneratedMatch, GeneratedSitOut } from "./types.js";
import { ALGORITHM_VERSION } from "./types.js";
import type { EngineState } from "./state.js";

export function computeFairness(
  state: EngineState,
  output: { matches: GeneratedMatch[]; sitOuts: GeneratedSitOut[] },
  input: EngineInput
): FairnessMetadata {
  const games = Array.from(state.gamesPlayed.values());
  const sitOuts = Array.from(state.sitOuts.values());

  // No players / no rounds generated: return neutral metadata (avoid Math.max(...[]) → -Infinity/NaN).
  if (games.length === 0) {
    return {
      algorithmVersion: ALGORITHM_VERSION,
      playersCount: input.players.length,
      courtsCount: input.courts.length,
      roundsGenerated: new Set(output.matches.map((m) => m.roundNumber)).size,
      fairnessScore: 1,
      fairnessPercent: 100,
      minGamesPerPlayer: 0,
      maxGamesPerPlayer: 0,
      notes: [],
    };
  }

  const minGames = Math.min(...games);
  const maxGames = Math.max(...games);

  let penalty = 0;
  const notes: string[] = [];

  // 1. Games played spread
  const maxSpread = maxGames - minGames;
  if (maxSpread > 1) {
    penalty += 0.2 * (maxSpread - 1);
    notes.push(`Games played spread is ${maxSpread} (ideal is ≤ 1)`);
  }

  // 2. Sit-outs spread (sitOuts is non-empty whenever games is)
  const sitOutSpread = Math.max(...sitOuts) - Math.min(...sitOuts);
  if (sitOutSpread > 1) {
    penalty += 0.3 * (sitOutSpread - 1);
    notes.push(`Sit-out spread is ${sitOutSpread} (ideal is ≤ 1)`);
  }

  // 3. Consecutive sit-outs: detect any player who sat in two consecutive output rounds
  const sitOutsByRound = new Map<number, Set<string>>();
  for (const so of output.sitOuts) {
    if (!sitOutsByRound.has(so.roundNumber)) sitOutsByRound.set(so.roundNumber, new Set());
    sitOutsByRound.get(so.roundNumber)!.add(so.playerId);
  }
  const sortedRounds = [...sitOutsByRound.keys()].sort((a, b) => a - b);
  let consecutiveSitOutCount = 0;
  for (let i = 1; i < sortedRounds.length; i++) {
    const prev = sitOutsByRound.get(sortedRounds[i - 1]!)!;
    const curr = sitOutsByRound.get(sortedRounds[i]!)!;
    for (const pid of curr) {
      if (prev.has(pid)) consecutiveSitOutCount++;
    }
  }
  if (consecutiveSitOutCount > 0) {
    penalty += 0.25 * consecutiveSitOutCount;
    notes.push(`${consecutiveSitOutCount} consecutive sit-out(s) detected — increase court count or reduce players`);
  }

  // 4. Repeat partners/opponents (check highest values)
  const maxPartners = Math.max(...Array.from(state.partnerCount.values()), 0);
  if (maxPartners > 1) {
    penalty += 0.1 * (maxPartners - 1);
    notes.push(`Repeated partners detected (max times: ${maxPartners})`);
  }

  const fairnessScore = Math.max(0, Math.min(1, 1 - penalty));
  const fairnessPercent = Math.round(fairnessScore * 100);

  // Count rounds generated by looking at output matches
  const roundsSet = new Set(output.matches.map(m => m.roundNumber));
  const roundsGenerated = roundsSet.size;

  return {
    algorithmVersion: ALGORITHM_VERSION,
    playersCount: input.players.length,
    courtsCount: input.courts.length,
    roundsGenerated,
    fairnessScore,
    fairnessPercent,
    minGamesPerPlayer: minGames,
    maxGamesPerPlayer: maxGames,
    notes,
  };
}